package direwolf

import (
	"net/http"
)

// RequestSetting is a prepared RequestSetting that generated by prepareRequestSetting().
// It came from your input in RequestSetting.
type RequestSetting struct {
	Method      string
	URL         string
	Params      Params
	Headers     http.Header
	Data        Data
	PostForm    PostForm
	Cookies     Cookies
	Proxy       string
	RedirectNum int
	Timeout     int
}

// setHeader get the key-value from Headers to RequestSetting.Headers.
func (req *RequestSetting) setHeader(h Headers) {
	req.Headers = http.Header{}
	for key, slice := range h {
		for _, value := range slice {
			req.Headers.Add(key, value)
		}
	}
}

// // setParams set RequestSetting.Params.Encode Params and join it to url.
// func (req *RequestSetting) setParams(p Params) {
// 	// for key, value := range p {

// 	// }
// 	req.URL = req.URL + "?" + req.Params.URLEncode() // add params to url
// }

// // setCookies set RequestSetting.Cookies
// func (req *RequestSetting) setCookies(c Cookies) {
// 	req.Cookies = url.Values(c)
// }

// NewRequestSetting new a default RequestSetting
func NewRequestSetting() *RequestSetting {
	return &RequestSetting{
		RedirectNum: 5,
		Timeout:     30,
	}
}
